services:
  backend:
    build:
      context: ./crochet-backend
      dockerfile: Dockerfile
    ports:
      - "5500:5500"
    restart: unless-stopped

  frontend:
    build:
      context: ./crochet-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: unless-stopped
    depends_on:
      - backend
